name: Build docker
on: push

jobs:
  push_to_registry:
    name: Build docker file for testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Generate uv.lock
        run: uv lock

      - name: Build Docker image
        run: docker build .