name: Default Branch Push CI

on:
  push:
    branches: [ "main" ]


# Specify concurrency such that only one workflow can run at a time
# * Different workflow files are not affected
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Define an autotagger job that creates tags on changes to master
  # Use #major #minor in merge commit messages to bump version beyond patch
  bump-tag:
    runs-on: ubuntu-latest
    # Better to run on merged PR's only, but can be run on pushes to main if desired
    if: >
      github.event_name == 'push' ||
      (
         contains(github.event_name, 'pull_request') && 
         github.event.action == 'closed' && 
         github.event.pull_request.merged == true
      )
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.OCF_BOT_PAT_TOKEN }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.OCF_BOT_PAT_TOKEN }}
          RELEASE_BRANCHES: main
          WITH_V: true
          DEFAULT_BUMP: patch
          GIT_API_TAGGING: false

  # Job for building container image
  # * Builds and pushes an OCI Container image to the registry defined in the environment variables
  build-container:
    runs-on: ubuntu-latest
    needs: bump-tag
    permissions:
      contents: read
      packages: write

    steps:
      # Do a non-shallow clone of the repo to ensure tags are present
      # * This allows setuptools-git-versioning to automatically set the version
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create and populate secrets.toml file
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: |
          touch src/.streamlit/secrets.toml
          echo "password = \"$APP_PASSWORD\"" >> src/.streamlit/secrets.toml


      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Tag the built image according to the event type
      # The event is a semver release, so use the version
      - name: Extract metadata (tags, labels) for Container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{version}},value=${{ needs.bump-tag.outputs.tag }}

      # Build and push the Container image to the registry
      # * Creates a multiplatform-aware image
      # * Pulls build cache from the registry and pushes new cache back
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

